chaps/urls.py
from django.urls import include, path

from django.contrib import admin
from chaps import views

app_name = 'chaps'

urlpatterns = [
  path('', views.index, name='index'),
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),

  path('about/', views.AboutView.as_view(), name='about'),
  # path('about/', views.about, name='about'),

  path('chaps/', views.ChapListView.as_view(), name='chap_list'),
  path('chap/new/', views.ChapCreateView.as_view(), name='chap_new'),
  path('<int:pk>/', views.ChapDetailView.as_view(), name='chap_detail'),
  path('chap/<int:pk>/update/', views.ChapUpdateView.as_view(), name='chap_update'),
  path('chap/<int:pk>/remove/', views.ChapDeleteView.as_view(), name='chap_remove'),

  path('chap/<int:pk>/add_pair_to_chap/', views.add_pair_to_chap, name='add_pair_to_chap'),
  path('chap/<int:pk>/pair/<int:id>/edit/', views.pair_update, name='pair_edit'),
  path('chap/<int:pk>/pair/<int:id>/remove/', views.pair_remove, name='pair_remove'),

  path('chap/<int:pk>/settings/', views.settings, name='settings'),
  path('chap/<int:pk>/callReset/', views.callReset, name='callReset'),

  path('chap/<int:pk>/<int:ct>/callPairs/', views.callPairs, name='callPairs'),
  path('chap/<int:pk>/<int:ct>/callPairs/next/', views.call_next, name='call_next'),

  path('chap/<int:pk>/pair/<int:id>/<int:ct>/<str:lr>/fail/', views.call_fail, name='call_fail'),
  path('chap/<int:pk>/pair/<int:id>/<int:ct>/<str:lr>/OK/', views.call_OK, name='call_OK'),
]

chaps_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('', include('chaps.urls')),
]

chaps_project/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
      {{ page_title|default:"Chapters" }}
    {% endblock title %}
  </title>

  {% block styles %}{% endblock styles %}

  {#bootstrap#}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e58ba3ceba.js" crossorigin="anonymous"></script>
  {#  <script src="https://use.fontawesome.com/ffda900719.js"></script>#}

  {# Custom CSS#}{#  <link rel="stylesheet" href="{% static '/css/chaps.css' %}">#}
  <link rel="stylesheet" href="{% static 'chaps.css' %}">

  {# Fonts#}
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>


<body>

  <!-- NAVBAR -->
  <div class="container">
    <div class="row nav">

      {% if user.is_authenticated %}

        <li class="nav-item nav-brand col-sm-2">
          <a class="nav-link active" href="{% url 'chaps:chap_list' %}"><h4>Chapters</h4></a>
        </li>

        <li class="nav-item col-sm-2">
          <a class="nav-link" href="{% url 'chaps:chap_new' %}"><i class="far fa-plus-square"></i> </a>
        </li>

        <li class="nav-item col-sm-1">
          <a class="nav-link" href="{% url 'chaps:about' %}">About</a>
        </li>

        <li class="nav-item col-sm-3">
          <a class="nav-link" href="http://www.edvin.co">EDV in Nittenau</a>
        </li>

        <li class="nav-item col-sm-2">
          <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>

        <li class="nav-item col-sm-2">
          <a class="nav-link" href="#">Willkommen: {{ user.username }}</a>
        </li>

      {% else %}

        <li class="nav-item nav-brand col-sm-2">
          <a class="nav-link active" href="#"><h4>Chapters</h4></a>
        </li>
        <li class="nav-item col-sm-1">
          <a class="nav-link" href="{% url 'chaps:about' %}">About</a>
        </li>

        <li class="nav-item col-sm-3">
          <a class="nav-link" href="http://www.edvin.co">EDV in Nittenau</a>
        </li>

        <li class="nav-item col-sm-3">
          <a class="nav-link" href="{% url 'login' %}"><span class="fa fa-user-o" aria-hidden="true"></span></a>
        </li>

      {% endif %}

      </div>
    </div>


  <!-- CONTENT BLOCK -->
  <div class="container">

          {% block content %}

          {% endblock content%}

  </div>


</body>
</html>