chaps/urls.py
from django.urls import include, path

from django.contrib import admin
from chaps import views

app_name = 'chaps'

urlpatterns = [
  path('', views.index, name='index'),
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),

  path('about/', views.AboutView.as_view(), name='about'),
  # path('about/', views.about, name='about'),

  path('chaps/', views.ChapListView.as_view(), name='chap_list'),
  path('chap/new/', views.ChapCreateView.as_view(), name='chap_new'),
  path('<int:pk>/', views.ChapDetailView.as_view(), name='chap_detail'),
  path('chap/<int:pk>/update/', views.ChapUpdateView.as_view(), name='chap_update'),
  path('chap/<int:pk>/remove/', views.ChapDeleteView.as_view(), name='chap_remove'),

  path('chap/<int:pk>/add_pair_to_chap/', views.add_pair_to_chap, name='add_pair_to_chap'),
  path('chap/<int:pk>/pair/<int:id>/edit/', views.pair_update, name='pair_edit'),
  path('chap/<int:pk>/pair/<int:id>/remove/', views.pair_remove, name='pair_remove'),

  path('chap/<int:pk>/settings/', views.settings, name='settings'),
  path('chap/<int:pk>/callReset/', views.callReset, name='callReset'),

  path('chap/<int:pk>/<int:ct>/callPairs/', views.callPairs, name='callPairs'),
  path('chap/<int:pk>/<int:ct>/callPairs/next/', views.call_next, name='call_next'),

  path('chap/<int:pk>/pair/<int:id>/<int:ct>/<str:lr>/fail/', views.call_fail, name='call_fail'),
  path('chap/<int:pk>/pair/<int:id>/<int:ct>/<str:lr>/OK/', views.call_OK, name='call_OK'),
]

chaps_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('', include('chaps.urls')),
]

chaps/models.py
from django.db import models
from django.urls import reverse

class Chap(models.Model):
  author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
  name = models.CharField(max_length=200)
  sum1 = models.IntegerField(default=0) # called
  sum2 = models.IntegerField(default=0) # called fail
  lr = models.CharField(max_length=2, default="L")  # Links or Rechts
  rs = models.CharField(max_length=2, default="r")  # random or serial
  toCallNum0 = models.IntegerField(default=0) # for serial calls

  def get_absolute_url(self):
    return reverse('chaps:chap_detail', kwargs={'pk':self.pk})

  def __str__(self):
    return '(id: ' + str(self.id) + ') ' + self.name + '(' + str(self.pairs.count()) +'/' + str(self.sum1) + '/' + str(self.sum2) + ')'


class Pair(models.Model):
  chap = models.ForeignKey('chaps.Chap', on_delete=models.CASCADE, related_name='pairs')
  textL = models.CharField(max_length=200)
  textR = models.CharField(max_length=200)
  status = models.IntegerField(default=0, blank=True)
  # 1: abgefragt OK, 2: abgefragt falsche Antwort

  # wird ausgegeben, wenn man das object pair anspricht
  def __str__(self):
    return "{0}: TextL = {1}; TextR = {2}; Status = {3}; ID={4},"\
      .format(self.chap.name, self.textL, self.textR, self.status, self.id)


class Call(models.Model):
  textAnswered = models.CharField(max_length=200)
  pairAskedID = models.IntegerField(default=0)
  callType = models.IntegerField(default=0) # All, Rest, Fail comes from button in chap_detail

  def __str__(self):
    return "pairAskedID = {0}: textAnswered = {1}; callType = {2};"\
      .format(self.pairAskedID, self.textAnswered, self.callType)

class IChap(models.Model):
  author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
  name = models.CharField(max_length=200)

  def __str__(self):
    return '(id: ' + str(self.id) + ') ' + self.name + '(' + str(self.Ipairs.count()) + ')'


class IPair(models.Model):
  chap = models.ForeignKey('chaps.IChap', on_delete=models.CASCADE, related_name='Ipairs')
  textL = models.CharField(max_length=200)
  textR = models.CharField(max_length=200)
  status = models.IntegerField(default=0, blank=True)

  def __str__(self):
    return "{0}: TextL = {1}; TextR = {2}; ID={3},"\
      .format(self.chap.name, self.textL, self.textR, self.id)

chaps/forms.py
from django import forms
from chaps.models import Chap, Pair, Call
from django.forms import Textarea, RadioSelect
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field

# from django.forms import inlineformset_factory

class ChapForm(forms.ModelForm):
  required_css_class = 'required'
  class Meta():
    model = Chap
    exclude = ('author', 'sum1', 'sum2', 'lr', 'rs', 'toCallNum0')
    # fields = ('name',)
    # fields = ('name', 'author', 'sum1', 'sum2', 'lr', 'rs', 'toCallNum0')
    widgets = {
      'name': Textarea(attrs={'cols': 40, 'rows':1}),
    }
    # exclude = ('author', 'sum1', 'sum2')
    # fields = ('name', 'author', 'sum1', 'sum2')

  # class Media:
  #   css = {'all': ('chaps.css',)}

# ChapFormset = inlineformset_factory(Chap, fields=('name'))


class CallForm(forms.ModelForm):
  required_css_class = 'required'
  class Meta():
    model = Call
    fields = ('textAnswered',)
    widgets = {
      'textAnswered': Textarea(attrs={'cols': 50, 'rows': 3, 'class':'form-control', 'autofocus': True}),
    }
  # class Media:
  #   css = {'all': ('form.css',)}


class SettingsForm(forms.Form):
  CHOICES_LR = [('L', 'Links'),
                ('R', 'Rechts')]
  CHOICES_rs = [('r', 'zufällige Abfrage'),
                ('s', 'der Reihe nach abfragen')]

  LR = forms.ChoiceField(
    label = "Abfrageart",
    choices = CHOICES_LR,
    widget = forms.RadioSelect,
    initial= 'L'
  )


class PairForm(forms.ModelForm):
  required_css_class = 'required'
  class Meta():
    model = Pair
    exclude = ('chap', 'status')
    # fields = ('chap', 'textL', 'textR', 'status')
    widgets = {
      'textL': Textarea(attrs={'cols': 55, 'rows':3, 'class':'form-control', 'autofocus': True}),
      'textR': Textarea(attrs={'cols': 55, 'rows':3}),
    }

  class Media:
    css = {'all': ('form.css',)}

chaps/views.py
from django.shortcuts import render, get_object_or_404, redirect
from chaps.models import Chap, Pair, Call
# from chaps.models import IChap, IPair for import (via AboutView)
from chaps.forms import ChapForm, PairForm, CallForm, SettingsForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from django.contrib.auth.models import User
import random, os


def index(request):
  return render(request, 'base.html')


class AboutView(TemplateView):
  template_name = 'chaps/about.html'

# def about(request):
#     act_dir = os.getcwd()
#     data_path = act_dir + "/chaps_project/static/Paar.txt"
#     author = request.user
#
#     n = 0
#     Kapitelalt = "99"
#     IChap.objects.all().delete()
#
#     object_list = Chap.objects.filter(author=author)
#     Chap.objects.filter(author=author).delete()
#
#     with open(data_path, 'r', encoding='utf-8', errors='replace') as datfile:
#       for line in datfile:
#         items_list = line.split(";")
#         if items_list[2] != Kapitelalt:
#           Kapitelalt = items_list[2]
#           Kapitelname = "LF 9-" + items_list[2]
#           Iobj = Chap(author=author, name=Kapitelname)
#           Iobj.save()
#
#         Pobj = Pair.objects.create(
#           chap=Iobj,
#           textL = items_list[3],
#           textR = items_list[4]
#         )
#         Pobj.save()
#         n += 1
#     object_list = Pair.objects.all()
#     return render(request, 'chaps/about.html', {'object_list': object_list})


class ChapListView(ListView):
  template_name = "chaps/chap_list.html"
  model = Chap
  context_object_name = 'chap'

  @method_decorator(login_required)
  def for_dec(self, request):
    pass

  def get_queryset(self):
    qs = super().get_queryset()
    qs = qs.filter(author_id=self.request.user.id)
    qs = qs.order_by("id")
    return qs


class ChapDetailView(DetailView):
  template_name = "chaps/chap_detail.html"
  model = Chap


class ChapCreateView(LoginRequiredMixin, CreateView):
  form_class = ChapForm
  template_name = "chaps/chap_form.html"
  success_url = reverse_lazy('chaps:chap_list')

  def form_valid(self, form):
    form.instance.author = self.request.user
    return super(ChapCreateView, self).form_valid(form)

  def get_objects(request, pk):
    chap = get_object_or_404(Chap, pk=pk)
    form = ChapForm
    return render(request, 'chaps/chap_form.html', {'form':form, 'object': chap})


class ChapUpdateView(LoginRequiredMixin, UpdateView):
  login_url = '/login/'
  model = Chap
  form_class = ChapForm

  def get_success_url(self):
    return reverse('chaps:chap_list')


class ChapDeleteView(DeleteView):
  model = Chap
  success_url = reverse_lazy('chaps:chap_list')

#____________________________________________________________
# Pair Views

@login_required
def add_pair_to_chap(request, pk):
  objChap= get_object_or_404(Chap, pk=pk)
  form = PairForm()
  context = {
    'form': form,
    'sender': "Create",
    'chap': objChap
  }
  if request.method == 'POST':
    form = PairForm(request.POST)
    if form.is_valid():
      pair = form.save(commit=False)
      pair.chap = objChap
      id_list = []
      pair_list = Pair.objects.all()
      for item in pair_list:
        id_list.append(item.id)
      id_list.sort()
      id = id_list[-1]
      pair.id = id + 1
      pair.save()

  return render(request, 'chaps/pair_form.html', context)


@login_required
def pair_update(request, pk, id):
  objPair = get_object_or_404(Pair, id=id)
  objChap = get_object_or_404(Chap, pk=pk)

  # pass the object as instance in form
  form = PairForm(request.POST or None, instance=objPair)

  # save the data from the form and
  # redirect to detail_view
  if form.is_valid():
    form.save()
    return redirect('chaps:chap_detail', pk=objChap.pk)
  else:
    context = {
      'form': form,
      'sender': "Update",
      'chap': objChap
    }
  return render(request, 'chaps/pair_form.html', context)


@login_required
def callPairs(request, pk, ct):

  global id
  chap = get_object_or_404(Chap, pk=pk)
  call = Call.objects.first() # for text (given and answered) there is only one object
  # ct calltype (all, called, fail) set via button
  call.callType = ct

  #_________
  if request.method == 'POST':

    form = CallForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      call.textAnswered = cd['textAnswered']
      call.save()
      objPair = chap.pairs.get(id=call.pairAskedID)
      if chap.lr == "L":
        textCalled = objPair.textR
      else:
        textCalled = objPair.textL

      if call.textAnswered == textCalled:
        call.textAnswered = "99"
        objPair.status = 1
        objPair.save()
        chap.sum1 = chap.pairs.filter(status=1).count()
        chap.sum2 = chap.pairs.filter(status=2).count()
        chap.sum1 = chap.sum1 + chap.sum2
        if ct == 0:
          chap.toCallNum0 += 1  # pair_list ändert sich nicht
        chap.save()
        return redirect('chaps:callPairs', pk=objPair.chap.pk, ct=call.callType)

      context = {'objChap': chap,
                 'objPair': objPair,
                 'ct': call.callType,
                 'lr': chap.lr,
                 'text': call.textAnswered}
      return render(request, 'chaps/check_form.html', context)

  else:
    # ct calltype (all=0, called=1, fail=2) set via button
    # lr: left, right and rs: random, serial set via chap_settings per chap

    pair_list = chap.pairs.all() # ct=0,1,2 alle abfragen

    if ct == 1:  # Rest abfragen
      pair_list = chap.pairs.filter(status=0)

    if ct == 2:  # Fehler abfragen
      pair_list = chap.pairs.filter(status=2)

    pair_list = pair_list.order_by("id")

    if pair_list.count() == 0:
      return render(request, 'chaps/chap_detail.html', {'chap': chap})
      # message und Abfrage zurücksetzen

    if chap.rs == "r":
      # erzeuge Zufallzahl zwischen 1 und Anzahl pairs
      if pair_list.count() == 1:
        ir = 1
      else:
        ir = random.randint(1, pair_list.count())

      objPair = pair_list[ir - 1]
      id = objPair.id
    else:
      # serial call
      if ct == 0:
        num = chap.toCallNum0
      else:
        num = 0

      if pair_list.count() - num <= 0:
        return render(request, 'chaps/chap_detail.html', {'chap': chap})

      objPair = pair_list[num]
      id = objPair.id

    if chap.lr == "L":
      pair_text = objPair.textL
    else:
      pair_text = objPair.textR

    call.pairAskedID = id
    call.save()

    form = CallForm(request.POST)

    context = {
      'form': form,
      'objChap': chap,
      'pair_text': pair_text,
      'pairs_count': chap.pairs.count(),
      'ct': call.callType,
    }
    return render(request, 'chaps/call_form.html', context)


@login_required
def call_next(request, pk, ct):
  chap = get_object_or_404(Chap, pk=pk)
  call = Call.objects.first()  # for text (given and answered) there is only one object
  # ct calltype (all, called, fail) set via button

  if ct == 0:
    chap.toCallNum0 += 1
    chap.save()

  return redirect('chaps:callPairs', pk, ct)


@login_required
def call_fail(request, pk, id, ct, lr):
  chap = get_object_or_404(Chap, pk=pk)

  objPair = chap.pairs.get(id=id)
  objPair.status = 2
  objPair.save()

  chap.sum1 = chap.pairs.filter(status=1).count() # called OK
  chap.sum2 = chap.pairs.filter(status=2).count() # called fail
  chap.sum1 = chap.sum1 + chap.sum2 # called

  # bei "alle abfragen" bleibt die pair_list gleich
  # Fehler abfragen: wenn nicht richtig beantwortet bleibt die pair_list gleich
  if ct == 0:
    chap.toCallNum0 += 1 # pair_list ändert sich nicht

  # nichts machen, da pair_list.filter(status=0) sich ändert
  # if ct == 1:
  #   pass

  # nichts machen, da pair_list.filter(status=2) sich ändert (wenn OK, oder nochmal in pair_list ist bei fail)
  # if ct == 2:
  #   pass

  chap.save()
  return redirect('chaps:callPairs', pk, ct)


@login_required
def call_OK(request, pk, id, ct, lr):
  chap = get_object_or_404(Chap, pk=pk)

  objPair = chap.pairs.get(id=id)
  objPair.status = 1
  objPair.save()

  chap.sum1 = chap.pairs.filter(status=1).count() # called OK
  chap.sum2 = chap.pairs.filter(status=2).count() # called fail
  chap.sum1 = chap.sum1 + chap.sum2 # called

  if ct == 0:
    chap.toCallNum0 += 1  # pair_list ändert sich nicht

  chap.save()
  return redirect('chaps:callPairs', pk, ct)


@login_required
def callReset(request, pk):
  chap = get_object_or_404(Chap, pk=pk)
  chap.sum1 = 0
  chap.sum2 = 0
  chap.toCallNum0 = 0
  chap.save()

  for objPair in chap.pairs.all():
    objPair.status = 0
    objPair.save()
  return render(request, 'chaps/chap_detail.html', {'chap': chap})


@login_required
def settings(request, pk):
  chap = get_object_or_404(Chap, pk=pk)
  if request.method == 'POST':
    chap.lr = request.POST['LR']
    chap.rs = request.POST['rs']
    chap.save()
  else:
    form = SettingsForm()
    context = {}
    context['chap'] = chap
    context['form'] = form
    return render(request, 'chaps/chap_settings.html', context)

  return redirect('chaps:chap_detail', pk=chap.pk)


@login_required
def pair_remove(request, pk, id):
  context = {}
  pair = get_object_or_404(Pair, id=id)
  chap = get_object_or_404(Chap, pk=pk)

  if request.method == "POST":
    pair.delete()
    return redirect('chaps:chap_detail', pk=pk)

  return render(request, 'chaps/pair_confirm_delete.html', {'objChap': chap, 'objPair': pair})

chaps/templates/chaps/about.html
{% extends 'base.html' %}

{% block content %}

  <h3>About Chapters</h3>
  <br>
  <p>Vielen Dank für die Nutzung von Chapters. Es erlaubt die Erstellung, Änderung und Abfrage von Textpaaren zu einer Themenüberschrift.</p>
  <br>
  <p>Dazu ist der Abfragemodus mit Call Settings (L/R,r/s) auf</p>
  <ul>
  <li>Links (L)/Rechts (R)</li>
  <li>zufällige Auswahl (r)/der Reihe nach (s)</li>
  </ul>
  <p>für jedes Kapitel separat einstellbar.</p>
  <br>
  <p>Mit Click auf Chapters werden alle Kapitel angezeigt. Die Angaben in Klammern rechts bedeuten:</p>
  <p>(Anzahl aller Textpaare/bereits abgefragte Textpaare/davon nicht richtig beantwortet).</p>
  <br>
  <p>Die Abfrage wird nur innerhalb eine Kapitels gestartet und eingestellt.</p>
  <ul>
  <li>All (x): alle Textpaare werden berücksichtigt</li>
  <li>Called (x): es werden nur die Textpaare abgefragt, die noch nicht abgefragt wurden.</li>
  <li>Failed (x): es werden nur die Textpaare abgefragt, die falsch beantwortet wurden.</li>
  <li>Reset: alle Textpaare werden auf "noch nicht abgefragt" gestellt; damit ist Called und All gleich der Anzahl der Textpaare und Failed=0</li>
  </ul>
  <p>Wenn die Zahl bei All und Called gleich ist und Failed (0), startet keine Anfrage.</p>
  <p>Der Status der Textpaare (gewusst oder nicht) wird mit Häkchen und Minuszeichen innerhalb der Kapitelansicht dargestellt.</p>

 <p>Innerhalb der Abfrage wird bei click auf Check gleich das nächste Textpaar abgefragt, falls die Antwort richtig war.</p>
 <p>Sonst wird die Antwort und der richtige Text untereinandergestellt. Der User entscheidet dann, ob die Antwort richtig oder falsch ist.</p>
 <p>"Leere Eingaben" sind nicht zulässig.</p>

 <p>Die Abfrage und das Erstellen von Textpaaren wird mit Cancel beendet.</p>

  <table>
    {% for item in object_list %}
      <tr>
        <td> {{ item.chap.author }}</td>
        <td> {{ item.chap.name }}</td>
        <td> {{ item.textL }}</td>
        <td> {{ item.textR }}</td>
      </tr>
    {% endfor %}
  </table>



{% endblock content %}

chaps/templates/chaps/call_form.html
{% extends 'base.html' %}
{% block styles %}{{ form.media }}{% endblock styles %}
{% block content %}

  {% if objChap.lr == "L" %}
    <table>
      <tr><td width="50%"><h3>{{ objChap.name }}: </h3></td><td><h6> Abfrage links, {{ objChap.rs }} </h6></td></tr>
    </table>
  {% else %}
    <h6>{{ objChap.name }}: Abfrage rechts, {{ objChap.rs }}</h6>
  {% endif %}
  <table>
    <td width="70%">&nbsp</td>
    <td width="10%" align="right"><a class="btn btn-success" href="#">All ({{ pairs_count }})</a></td>
    <td width="10%" align="right"><a class="btn btn-info" href="#">Called ({{ objChap.sum1 }})</a></td>
    <td width="10%" align="right"><a class="btn btn-danger" href="#">Failed ({{ objChap.sum2 }})</a></td>
  </table>
  <hr>

  <table>
    <tr>
      <td width="50%"><h4>Links</h4></td>
      <td width="50%"><h4>Rechts</h4></td>
    </tr>
  <tr><br></tr>
  </table>


  <form action="" method="POST">{% csrf_token %}

    <table>
      <tr>
        {% if objChap.lr == "L" %}
          <td width="50%">{{ pair_text }}</td>
          <td width="50%">{{ form.textAnswered }}</td>
        {% else %}
          <td width="50%">{{ form.textAnswered }}</td>
          <td width="50%">{{ pair_text }}</td>
        {% endif %}
       </tr>
      </table>

    <table style="margin-top:30px">
      <tr>
        <td width="70%">&nbsp</td>
        <td width="10%"><a class="btn btn-secondary" href="{% url 'chaps:chap_detail' pk=objChap.pk %}">Cancel</a></td>
        <td width="10%"><button type="submit" value="Submit" class="btn btn-info" >Check</button></td>
        <td width="10%"><a class="btn btn-success" href="{% url 'chaps:call_next' pk=objChap.pk ct=ct %}">Next</a></td>
      </tr>
    </table>

  </form>

{% endblock content %}

chaps/templates/chaps/chap_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <form method="POST">{% csrf_token %}
{#    <h4>Kapitel</h4>#}
    <h3>"{{ object.name }}" mit {{ object.pairs.count }} Einträgen </h3>
    <br>
    <h4>wirklich löschen?</h4>
    <a style="margin-right: 40px;" class="btn btn-secondary" href="{% url 'chaps:chap_list' %}">Cancel</a>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

chaps/templates/chaps/chap_detail.html
{% extends 'base.html' %}

{% block title %}{{ chap.name }}{% endblock title %}
{% block content %}


  <table border="0">
    <tr>
      <td width="400px"><h3>{{ chap.name }}</h3></td>
      <td width="20px"  align="right"><a href="{% url 'chaps:add_pair_to_chap' pk=chap.pk %}"> <i class="far fa-plus-square"></i></a></td>
      <td width="130px" align="right"><a class="btn btn-outline-secondary" href="{% url 'chaps:settings' pk=chap.pk %}">Settings ({{ chap.lr }}, {{ chap.rs }}):</a></td>
      <td width="100px" align="right"><a class="btn btn-success" href="{% url 'chaps:callPairs' pk=chap.pk ct=0 %}">All ({{ chap.pairs.count }})</a></td>
      <td width="100px" align="right"><a class="btn btn-info" href="{% url 'chaps:callPairs' pk=chap.pk ct=1 %}">Called ({{ chap.sum1 }})</a></td>
      <td width="100px" align="right"><a class="btn btn-danger" href="{% url 'chaps:callPairs' pk=chap.pk ct=2 %}">Failed ({{ chap.sum2 }})</a></td>
      <td width="100px" align="right"><a class="btn btn-warning" href="{% url 'chaps:callReset' pk=chap.pk %}">Reset</a></td>
    </tr>
  </table>
  <hr>


{#  <div class="container">#}
    {% if chap.pairs.count > 0 %}
      {% if user.is_authenticated %}
        <table border="0">
          {% for pair in chap.pairs.all|dictsort:"id" %}
            <tr>
              <td width="40%">{{ pair.textL }}</td>
              <td width="40%">{{ pair.textR }}</td>
              <td width="5%" align="right"><p><a  href="{% url 'chaps:pair_edit' pk=chap.pk id=pair.pk %}"><i class="fa fa-pencil" aria-hidden="true"></i></a></p></td>
              <td width="5%" align="right"><p><a  href="{% url 'chaps:pair_remove' pk=chap.pk id=pair.pk %}"><span class="fa fa-trash-o" aria-hidden="true"></span></a></p></td>
              {% if pair.status == 1 %}
                <td width="5%" align="right"><p><i class="fa fa-check" aria-hidden="true" style="color:green"></i></p></td>
              {% elif pair.status == 2 %}
                <td width="5%" align="right"><p><span class="fas fa-minus" style="color:red"></span></p></td>
              {% endif %}
            </tr>
          {% endfor %}
      </table>
 {% endif %}
    {% else %}
      <p>Noch keine Texte vorhanden</p>
    {% endif %}
{#  </div>#}

{% endblock content %}

chaps/templates/chaps/chap_list.html
{% extends 'base.html' %}

{% block title %}Liste der Kapitel{% endblock title %}

{% block content %}

{% if object_list.count > 0 %}
  {% for chap in object_list %}
    <table border="0">
      <tr>
        <td width="75%"><h5><a href="{% url 'chaps:chap_detail' pk=chap.pk %}">{{ chap.name }}</a></h5></td>
        <td width="15%"><h5>({{ chap.pairs.count }}/{{ chap.sum1 }}/{{ chap.sum2 }})</h5></td>

        <td width="5%" align="right"><a  href="{% url 'chaps:chap_update' pk=chap.pk %}"><i aria-hidden class="fa fa-pencil"></i></a></td>
        <td width="5%" align="right"><a  href="{% url 'chaps:chap_remove' pk=chap.pk %}"><i aria-hidden class="fa fa-trash-o" ></i></a></td>

      </tr>

    </table>
  {% endfor %}
{% else %}
  <p>noch keine Kapitel vorhanden!</p>
{% endif %}

{% endblock content %}

chaps/templates/chaps/check_form.html
{% extends 'base.html' %}
{% block styles %}{{ form.media }}{% endblock styles %}
{% block content %}

  {% if lr == "L" %}
    <table>
      <tr><td width="50%"><h3>{{ objChap.name }}: </h3></td><td><h4> Abfrage links</h4></td></tr>
    </table>
  {% else %}
    <h3>{{ objChap.name }}</h3><h4>Abfrage rechts:</h4>
  {% endif %}
  <hr>

<table>
  <tr>
    <td width="50%"><h4>Links</h4></td>
    <td><h4>Rechts</h4></td>
  </tr>

  <br>



  {% if lr == "L" %}
    <tr>
      <td>{{ objPair.textL }}</td>
      <td><span style="background-color: lightsteelblue">{{ objPair.textR }}</span></td>
    </tr>
      <tr>
    <td>&nbsp</td>
    <td>&nbsp</td>
  </tr>
    <tr>
      <td>&nbsp</td>
      <td><span style="background-color: lightsteelblue">{{ text }}</span></td>
    </tr>

  {% else %}

    <tr>
      <td><span style="background-color: lightsteelblue">{{ objPair.textL }}</span></td>
      <td>{{ objPair.textR }}</td>
    </tr>
      <tr>
    <td>&nbsp</td>
    <td>&nbsp</td>
  </tr>
    <tr>
      <td><span style="background-color: lightsteelblue">{{ text }}</span></td>
      <td>&nbsp</td>
    </tr>
  {% endif %}

  <tr>
    <td>&nbsp</td>
  </tr>

  </table>

  <table style="margin-top: 30px" width="100%">
  <tr>
    <td width="50%"><a class="btn btn-secondary" tabindex="1" href="{% url 'chaps:chap_detail' pk=objChap.pk %}">Cancel</a></td>
    <td width="25%"><a class="btn btn-success" tabindex="2" href="{% url 'chaps:call_OK' pk=objChap.pk id=objPair.id ct=ct lr=lr %}"><span class="fas fa-thumbs-up"></span></a></td>
    <td width="25%"><a class="btn btn-danger" tabindex="3" href="{% url 'chaps:call_fail' pk=objChap.pk id=objPair.id ct=ct lr=lr %}"><span class="fas fa-thumbs-down"></span></a></td>
  </tr>
</table>



{% endblock content %}